"use client";

import { useState } from "react";
import { formatDate, formatPrice } from "@/lib/utils";
import { Gift, Plus, Search, Loader2, Copy, Check } from "lucide-react";

interface Voucher {
  id: string;
  code: string;
  description: string | null;
  purchaserName: string | null;
  purchaserEmail: string | null;
  status: string;
  amountValue: number | null;
  isAutoGenerated: boolean;
  expiresAt: string | null;
  redeemedAt: string | null;
  createdAt: string;
  owner: { firstName: string | null; lastName: string | null; email: string } | null;
}

interface Service {
  id: string;
  name: string;
  price: number;
}

const STATUS_LABELS: Record<string, { label: string; className: string }> = {
  ACTIVE: { label: "Actif", className: "bg-green-100 text-green-700" },
  REDEEMED: { label: "Utilisé", className: "bg-secondary text-muted-foreground" },
  EXPIRED: { label: "Expiré", className: "bg-red-100 text-red-600" },
  CANCELLED: { label: "Annulé", className: "bg-secondary text-muted-foreground" },
};

export function BonsCadeauxAdmin({ initialVouchers, services }: { initialVouchers: Voucher[]; services: Service[] }) {
  const [vouchers, setVouchers] = useState(initialVouchers);
  const [search, setSearch] = useState("");
  const [showForm, setShowForm] = useState(false);
  const [copiedId, setCopiedId] = useState<string | null>(null);
  const [form, setForm] = useState({
    serviceTypeId: "",
    description: "",
    purchaserName: "",
    purchaserEmail: "",
    ownerEmail: "",
    expiresInDays: 365,
  });
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");

  const filtered = vouchers.filter((v) => {
    const q = search.toLowerCase();
    return !q ||
      v.code.toLowerCase().includes(q) ||
      (v.purchaserName ?? "").toLowerCase().includes(q) ||
      (v.purchaserEmail ?? "").toLowerCase().includes(q) ||
      (v.owner?.email ?? "").toLowerCase().includes(q);
  });

  async function createVoucher() {
    if (!form.description && !form.serviceTypeId) { setError("Choisissez un service ou ajoutez une description."); return; }
    setLoading(true);
    setError("");
    const res = await fetch("/api/admin/bons-cadeaux", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        ...form,
        description: form.description || (services.find((s) => s.id === form.serviceTypeId)?.name ?? "Bon cadeau"),
        serviceTypeId: form.serviceTypeId || undefined,
      }),
    });
    const data = await res.json();
    if (res.ok) {
      setVouchers([data, ...vouchers]);
      setShowForm(false);
      setForm({ serviceTypeId: "", description: "", purchaserName: "", purchaserEmail: "", ownerEmail: "", expiresInDays: 365 });
    } else {
      setError(data.error ?? "Erreur");
    }
    setLoading(false);
  }

  async function copyCode(code: string, id: string) {
    await navigator.clipboard.writeText(code);
    setCopiedId(id);
    setTimeout(() => setCopiedId(null), 2000);
  }

  const stats = {
    total: vouchers.length,
    active: vouchers.filter((v) => v.status === "ACTIVE").length,
    redeemed: vouchers.filter((v) => v.status === "REDEEMED").length,
    auto: vouchers.filter((v) => v.isAutoGenerated).length,
  };

  return (
    <div className="space-y-6">
      {/* Stats */}
      <div className="grid grid-cols-2 sm:grid-cols-4 gap-3">
        {[
          { label: "Total", value: stats.total },
          { label: "Actifs", value: stats.active },
          { label: "Utilisés", value: stats.redeemed },
          { label: "Auto-générés", value: stats.auto },
        ].map((s) => (
          <div key={s.label} className="bg-card border border-border rounded-xl p-4 text-center">
            <p className="text-2xl font-bold text-foreground">{s.value}</p>
            <p className="text-xs text-muted-foreground mt-1">{s.label}</p>
          </div>
        ))}
      </div>

      {/* Toolbar */}
      <div className="flex flex-col sm:flex-row gap-3 items-start sm:items-center justify-between">
        <div className="relative flex-1 max-w-sm">
          <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-muted-foreground" />
          <input
            type="text"
            placeholder="Rechercher par code, acheteur..."
            value={search}
            onChange={(e) => setSearch(e.target.value)}
            className="w-full border border-input rounded-lg pl-9 pr-3 py-2 text-sm bg-background focus:outline-none focus:ring-2 focus:ring-ring"
          />
        </div>
        <button
          onClick={() => setShowForm(!showForm)}
          className="flex items-center gap-2 bg-primary text-primary-foreground px-4 py-2 rounded-lg text-sm font-medium hover:bg-primary/90 transition-colors shrink-0"
        >
          <Plus className="w-4 h-4" /> Créer un bon cadeau
        </button>
      </div>

      {/* Formulaire création */}
      {showForm && (
        <div className="bg-card border border-border rounded-xl p-6">
          <h3 className="font-semibold text-foreground mb-4">Nouveau bon cadeau manuel</h3>
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
            <div>
              <label className="block text-xs text-muted-foreground mb-1">Service (optionnel)</label>
              <select
                value={form.serviceTypeId}
                onChange={(e) => setForm({ ...form, serviceTypeId: e.target.value })}
                className="w-full border border-input rounded-lg px-3 py-2 text-sm bg-background focus:outline-none focus:ring-2 focus:ring-ring"
              >
                <option value="">Choisir un service...</option>
                {services.map((s) => (
                  <option key={s.id} value={s.id}>{s.name} — {formatPrice(s.price)}</option>
                ))}
              </select>
            </div>
            <div>
              <label className="block text-xs text-muted-foreground mb-1">Description *</label>
              <input
                type="text"
                value={form.description}
                onChange={(e) => setForm({ ...form, description: e.target.value })}
                placeholder="Ex: Bon cadeau anniversaire"
                className="w-full border border-input rounded-lg px-3 py-2 text-sm bg-background focus:outline-none focus:ring-2 focus:ring-ring"
              />
            </div>
            <div>
              <label className="block text-xs text-muted-foreground mb-1">Nom de l'acheteur</label>
              <input type="text" value={form.purchaserName} onChange={(e) => setForm({ ...form, purchaserName: e.target.value })} placeholder="Marie Dupont" className="w-full border border-input rounded-lg px-3 py-2 text-sm bg-background focus:outline-none focus:ring-2 focus:ring-ring" />
            </div>
            <div>
              <label className="block text-xs text-muted-foreground mb-1">Email acheteur</label>
              <input type="email" value={form.purchaserEmail} onChange={(e) => setForm({ ...form, purchaserEmail: e.target.value })} placeholder="acheteur@email.fr" className="w-full border border-input rounded-lg px-3 py-2 text-sm bg-background focus:outline-none focus:ring-2 focus:ring-ring" />
            </div>
            <div>
              <label className="block text-xs text-muted-foreground mb-1">Email du bénéficiaire (pour l'attribuer directement)</label>
              <input type="email" value={form.ownerEmail} onChange={(e) => setForm({ ...form, ownerEmail: e.target.value })} placeholder="beneficiaire@email.fr" className="w-full border border-input rounded-lg px-3 py-2 text-sm bg-background focus:outline-none focus:ring-2 focus:ring-ring" />
            </div>
            <div>
              <label className="block text-xs text-muted-foreground mb-1">Validité (jours)</label>
              <input type="number" value={form.expiresInDays} onChange={(e) => setForm({ ...form, expiresInDays: parseInt(e.target.value) })} min={1} className="w-full border border-input rounded-lg px-3 py-2 text-sm bg-background focus:outline-none focus:ring-2 focus:ring-ring" />
            </div>
          </div>
          {error && <p className="text-destructive text-sm mt-3">{error}</p>}
          <div className="flex gap-3 mt-4">
            <button onClick={() => setShowForm(false)} className="flex-1 border border-border py-2 rounded-lg text-sm hover:bg-secondary">Annuler</button>
            <button onClick={createVoucher} disabled={loading} className="flex-1 bg-primary text-primary-foreground py-2 rounded-lg text-sm font-medium hover:bg-primary/90 disabled:opacity-50 flex items-center justify-center gap-2">
              {loading && <Loader2 className="w-4 h-4 animate-spin" />}
              Créer le bon cadeau
            </button>
          </div>
        </div>
      )}

      {/* Tableau */}
      <div className="bg-card border border-border rounded-xl overflow-hidden">
        <table className="w-full text-sm">
          <thead className="bg-secondary/50 border-b border-border">
            <tr>
              <th className="text-left px-4 py-3 font-medium text-muted-foreground">Code</th>
              <th className="text-left px-4 py-3 font-medium text-muted-foreground">Description</th>
              <th className="text-left px-4 py-3 font-medium text-muted-foreground hidden sm:table-cell">Bénéficiaire</th>
              <th className="text-left px-4 py-3 font-medium text-muted-foreground hidden md:table-cell">Expire</th>
              <th className="text-center px-4 py-3 font-medium text-muted-foreground">Statut</th>
            </tr>
          </thead>
          <tbody className="divide-y divide-border">
            {filtered.length === 0 && (
              <tr><td colSpan={5} className="text-center py-10 text-muted-foreground">Aucun bon cadeau</td></tr>
            )}
            {filtered.map((v) => {
              const statusInfo = STATUS_LABELS[v.status] ?? { label: v.status, className: "bg-secondary" };
              return (
                <tr key={v.id} className="hover:bg-secondary/20">
                  <td className="px-4 py-3">
                    <div className="flex items-center gap-2">
                      <span className="font-mono text-sm font-bold text-foreground">{v.code}</span>
                      <button onClick={() => copyCode(v.code, v.id)} className="p-1 text-muted-foreground hover:text-primary transition-colors">
                        {copiedId === v.id ? <Check className="w-3.5 h-3.5 text-green-600" /> : <Copy className="w-3.5 h-3.5" />}
                      </button>
                    </div>
                    {v.isAutoGenerated && <span className="text-xs text-muted-foreground">Auto-généré</span>}
                  </td>
                  <td className="px-4 py-3 text-foreground">
                    <p>{v.description ?? "—"}</p>
                    {v.amountValue && <p className="text-xs text-primary font-medium">{formatPrice(v.amountValue)}</p>}
                  </td>
                  <td className="px-4 py-3 hidden sm:table-cell">
                    {v.owner ? (
                      <div>
                        <p className="text-foreground text-xs">{v.owner.firstName} {v.owner.lastName}</p>
                        <p className="text-muted-foreground text-xs">{v.owner.email}</p>
                      </div>
                    ) : (
                      <span className="text-muted-foreground text-xs">Non réclamé</span>
                    )}
                  </td>
                  <td className="px-4 py-3 text-muted-foreground text-xs hidden md:table-cell">
                    {v.expiresAt ? formatDate(v.expiresAt) : "—"}
                  </td>
                  <td className="px-4 py-3 text-center">
                    <span className={`text-xs px-2 py-0.5 rounded-full font-medium ${statusInfo.className}`}>
                      {statusInfo.label}
                    </span>
                  </td>
                </tr>
              );
            })}
          </tbody>
        </table>
      </div>
    </div>
  );
}
