import { NextRequest, NextResponse } from "next/server";
import { auth } from "@/lib/auth";
import { prisma } from "@/lib/prisma";
import { z } from "zod";

async function checkAdmin() {
  const session = await auth();
  return session?.user?.role === "ADMIN" ? session : null;
}

export async function GET() {
  if (!(await checkAdmin())) return NextResponse.json({ error: "Accès refusé" }, { status: 403 });

  const vouchers = await prisma.giftVoucher.findMany({
    include: {
      owner: { select: { firstName: true, lastName: true, email: true } },
    },
    orderBy: { createdAt: "desc" },
  });

  return NextResponse.json(
    vouchers.map((v) => ({
      ...v,
      amountValue: v.amountValue ? Number(v.amountValue) : null,
    }))
  );
}

export async function POST(req: NextRequest) {
  if (!(await checkAdmin())) return NextResponse.json({ error: "Accès refusé" }, { status: 403 });

  const schema = z.object({
    serviceTypeId: z.string().optional(),
    description: z.string(),
    purchaserName: z.string().optional(),
    purchaserEmail: z.string().email().optional(),
    ownerEmail: z.string().email().optional(), // si on veut directement l'attribuer
    expiresInDays: z.number().default(365),
  });

  const parsed = schema.safeParse(await req.json());
  if (!parsed.success) return NextResponse.json({ error: parsed.error.flatten() }, { status: 400 });

  const { serviceTypeId, description, purchaserName, purchaserEmail, ownerEmail, expiresInDays } = parsed.data;

  // Trouver le propriétaire si email fourni
  let ownerId: string | undefined;
  if (ownerEmail) {
    const owner = await prisma.user.findUnique({ where: { email: ownerEmail } });
    if (owner) ownerId = owner.id;
  }

  const code = generateCode();
  const expiresAt = new Date();
  expiresAt.setDate(expiresAt.getDate() + expiresInDays);

  let servicePrice: number | undefined;
  if (serviceTypeId) {
    const svc = await prisma.serviceType.findUnique({ where: { id: serviceTypeId } });
    if (svc) servicePrice = Number(svc.price);
  }

  const voucher = await prisma.giftVoucher.create({
    data: {
      code,
      serviceTypeId: serviceTypeId || undefined,
      description,
      purchaserName,
      purchaserEmail,
      ownerId,
      status: "ACTIVE",
      isAutoGenerated: false,
      expiresAt,
      amountValue: servicePrice,
    },
  });

  return NextResponse.json({ ...voucher, amountValue: voucher.amountValue ? Number(voucher.amountValue) : null });
}

function generateCode(): string {
  const chars = "ABCDEFGHJKLMNPQRSTUVWXYZ23456789";
  let code = "";
  for (let i = 0; i < 8; i++) {
    if (i === 4) code += "-";
    code += chars[Math.floor(Math.random() * chars.length)];
  }
  return code;
}
